// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using desafioKw.Data;

#nullable disable

namespace desafioKw.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220704145212_ajuste")]
    partial class ajuste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("desafioKw.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Equipe")
                        .HasColumnType("integer");

                    b.Property<int>("Fase")
                        .HasColumnType("integer");

                    b.Property<string>("Projeto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SaldoHora")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<string>("TituloCard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("posicaoHorizontal")
                        .HasColumnType("integer");

                    b.Property<int>("posicaoVertical")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("cartoes");
                });
#pragma warning restore 612, 618
        }
    }
}
